# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63lient.proto\"&\n\x0e\x43omposePackage\x12\x14\n\x0c\x63ompose_file\x18\x01 \x01(\x0c\"\'\n\x11\x43omposeIdentifier\x12\x12\n\ncompose_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\xa8\x04\n\x14ResourceGroupCompose\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x04pops\x18\x02 \x03(\x0b\x32 .ResourceGroupCompose.PoPCompose\x12\x36\n\x08networks\x18\x03 \x03(\x0b\x32$.ResourceGroupCompose.NetworkCompose\x12.\n\x04vdus\x18\x04 \x03(\x0b\x32 .ResourceGroupCompose.VDUCompose\x1a\x35\n\nPoPCompose\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11interfaceEndpoint\x18\x02 \x01(\t\x1a\x32\n\x14MetadataEntryCompose\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1aP\n\x0eNetworkCompose\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07poPName\x18\x02 \x01(\t\x12\x0c\n\x04\x63idr\x18\x03 \x01(\t\x12\x11\n\tnetworkId\x18\x04 \x01(\t\x1a\xac\x01\n\nVDUCompose\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\timageName\x18\x02 \x01(\t\x12\x0f\n\x07netName\x18\x03 \x01(\t\x12\x0f\n\x07poPName\x18\x04 \x01(\t\x12\x11\n\tcomputeId\x18\x05 \x01(\t\x12\n\n\x02ip\x18\x06 \x01(\t\x12<\n\x08metadata\x18\x07 \x03(\x0b\x32*.ResourceGroupCompose.MetadataEntryCompose2v\n\x0e\x43omposeHandler\x12\x35\n\tUpCompose\x12\x0f.ComposePackage\x1a\x15.ResourceGroupCompose\"\x00\x12-\n\rRemoveCompose\x12\x12.ComposeIdentifier\x1a\x06.Empty\"\x00\x42\x02P\x01\x62\x06proto3')
)




_COMPOSEPACKAGE = _descriptor.Descriptor(
  name='ComposePackage',
  full_name='ComposePackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compose_file', full_name='ComposePackage.compose_file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=54,
)


_COMPOSEIDENTIFIER = _descriptor.Descriptor(
  name='ComposeIdentifier',
  full_name='ComposeIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compose_id', full_name='ComposeIdentifier.compose_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=95,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=104,
)


_RESOURCEGROUPCOMPOSE_POPCOMPOSE = _descriptor.Descriptor(
  name='PoPCompose',
  full_name='ResourceGroupCompose.PoPCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ResourceGroupCompose.PoPCompose.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interfaceEndpoint', full_name='ResourceGroupCompose.PoPCompose.interfaceEndpoint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=350,
)

_RESOURCEGROUPCOMPOSE_METADATAENTRYCOMPOSE = _descriptor.Descriptor(
  name='MetadataEntryCompose',
  full_name='ResourceGroupCompose.MetadataEntryCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ResourceGroupCompose.MetadataEntryCompose.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ResourceGroupCompose.MetadataEntryCompose.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=402,
)

_RESOURCEGROUPCOMPOSE_NETWORKCOMPOSE = _descriptor.Descriptor(
  name='NetworkCompose',
  full_name='ResourceGroupCompose.NetworkCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ResourceGroupCompose.NetworkCompose.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poPName', full_name='ResourceGroupCompose.NetworkCompose.poPName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cidr', full_name='ResourceGroupCompose.NetworkCompose.cidr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networkId', full_name='ResourceGroupCompose.NetworkCompose.networkId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=484,
)

_RESOURCEGROUPCOMPOSE_VDUCOMPOSE = _descriptor.Descriptor(
  name='VDUCompose',
  full_name='ResourceGroupCompose.VDUCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ResourceGroupCompose.VDUCompose.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imageName', full_name='ResourceGroupCompose.VDUCompose.imageName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='netName', full_name='ResourceGroupCompose.VDUCompose.netName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='poPName', full_name='ResourceGroupCompose.VDUCompose.poPName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computeId', full_name='ResourceGroupCompose.VDUCompose.computeId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='ResourceGroupCompose.VDUCompose.ip', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='ResourceGroupCompose.VDUCompose.metadata', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=659,
)

_RESOURCEGROUPCOMPOSE = _descriptor.Descriptor(
  name='ResourceGroupCompose',
  full_name='ResourceGroupCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ResourceGroupCompose.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pops', full_name='ResourceGroupCompose.pops', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networks', full_name='ResourceGroupCompose.networks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vdus', full_name='ResourceGroupCompose.vdus', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESOURCEGROUPCOMPOSE_POPCOMPOSE, _RESOURCEGROUPCOMPOSE_METADATAENTRYCOMPOSE, _RESOURCEGROUPCOMPOSE_NETWORKCOMPOSE, _RESOURCEGROUPCOMPOSE_VDUCOMPOSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=659,
)

_RESOURCEGROUPCOMPOSE_POPCOMPOSE.containing_type = _RESOURCEGROUPCOMPOSE
_RESOURCEGROUPCOMPOSE_METADATAENTRYCOMPOSE.containing_type = _RESOURCEGROUPCOMPOSE
_RESOURCEGROUPCOMPOSE_NETWORKCOMPOSE.containing_type = _RESOURCEGROUPCOMPOSE
_RESOURCEGROUPCOMPOSE_VDUCOMPOSE.fields_by_name['metadata'].message_type = _RESOURCEGROUPCOMPOSE_METADATAENTRYCOMPOSE
_RESOURCEGROUPCOMPOSE_VDUCOMPOSE.containing_type = _RESOURCEGROUPCOMPOSE
_RESOURCEGROUPCOMPOSE.fields_by_name['pops'].message_type = _RESOURCEGROUPCOMPOSE_POPCOMPOSE
_RESOURCEGROUPCOMPOSE.fields_by_name['networks'].message_type = _RESOURCEGROUPCOMPOSE_NETWORKCOMPOSE
_RESOURCEGROUPCOMPOSE.fields_by_name['vdus'].message_type = _RESOURCEGROUPCOMPOSE_VDUCOMPOSE
DESCRIPTOR.message_types_by_name['ComposePackage'] = _COMPOSEPACKAGE
DESCRIPTOR.message_types_by_name['ComposeIdentifier'] = _COMPOSEIDENTIFIER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ResourceGroupCompose'] = _RESOURCEGROUPCOMPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComposePackage = _reflection.GeneratedProtocolMessageType('ComposePackage', (_message.Message,), dict(
  DESCRIPTOR = _COMPOSEPACKAGE,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:ComposePackage)
  ))
_sym_db.RegisterMessage(ComposePackage)

ComposeIdentifier = _reflection.GeneratedProtocolMessageType('ComposeIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _COMPOSEIDENTIFIER,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:ComposeIdentifier)
  ))
_sym_db.RegisterMessage(ComposeIdentifier)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

ResourceGroupCompose = _reflection.GeneratedProtocolMessageType('ResourceGroupCompose', (_message.Message,), dict(

  PoPCompose = _reflection.GeneratedProtocolMessageType('PoPCompose', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCEGROUPCOMPOSE_POPCOMPOSE,
    __module__ = 'client_pb2'
    # @@protoc_insertion_point(class_scope:ResourceGroupCompose.PoPCompose)
    ))
  ,

  MetadataEntryCompose = _reflection.GeneratedProtocolMessageType('MetadataEntryCompose', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCEGROUPCOMPOSE_METADATAENTRYCOMPOSE,
    __module__ = 'client_pb2'
    # @@protoc_insertion_point(class_scope:ResourceGroupCompose.MetadataEntryCompose)
    ))
  ,

  NetworkCompose = _reflection.GeneratedProtocolMessageType('NetworkCompose', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCEGROUPCOMPOSE_NETWORKCOMPOSE,
    __module__ = 'client_pb2'
    # @@protoc_insertion_point(class_scope:ResourceGroupCompose.NetworkCompose)
    ))
  ,

  VDUCompose = _reflection.GeneratedProtocolMessageType('VDUCompose', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCEGROUPCOMPOSE_VDUCOMPOSE,
    __module__ = 'client_pb2'
    # @@protoc_insertion_point(class_scope:ResourceGroupCompose.VDUCompose)
    ))
  ,
  DESCRIPTOR = _RESOURCEGROUPCOMPOSE,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:ResourceGroupCompose)
  ))
_sym_db.RegisterMessage(ResourceGroupCompose)
_sym_db.RegisterMessage(ResourceGroupCompose.PoPCompose)
_sym_db.RegisterMessage(ResourceGroupCompose.MetadataEntryCompose)
_sym_db.RegisterMessage(ResourceGroupCompose.NetworkCompose)
_sym_db.RegisterMessage(ResourceGroupCompose.VDUCompose)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('P\001'))

_COMPOSEHANDLER = _descriptor.ServiceDescriptor(
  name='ComposeHandler',
  full_name='ComposeHandler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=661,
  serialized_end=779,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpCompose',
    full_name='ComposeHandler.UpCompose',
    index=0,
    containing_service=None,
    input_type=_COMPOSEPACKAGE,
    output_type=_RESOURCEGROUPCOMPOSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveCompose',
    full_name='ComposeHandler.RemoveCompose',
    index=1,
    containing_service=None,
    input_type=_COMPOSEIDENTIFIER,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPOSEHANDLER)

DESCRIPTOR.services_by_name['ComposeHandler'] = _COMPOSEHANDLER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ComposeHandlerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.UpCompose = channel.unary_unary(
          '/ComposeHandler/UpCompose',
          request_serializer=ComposePackage.SerializeToString,
          response_deserializer=ResourceGroupCompose.FromString,
          )
      self.RemoveCompose = channel.unary_unary(
          '/ComposeHandler/RemoveCompose',
          request_serializer=ComposeIdentifier.SerializeToString,
          response_deserializer=Empty.FromString,
          )


  class ComposeHandlerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def UpCompose(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def RemoveCompose(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ComposeHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'UpCompose': grpc.unary_unary_rpc_method_handler(
            servicer.UpCompose,
            request_deserializer=ComposePackage.FromString,
            response_serializer=ResourceGroupCompose.SerializeToString,
        ),
        'RemoveCompose': grpc.unary_unary_rpc_method_handler(
            servicer.RemoveCompose,
            request_deserializer=ComposeIdentifier.FromString,
            response_serializer=Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ComposeHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaComposeHandlerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def UpCompose(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def RemoveCompose(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaComposeHandlerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def UpCompose(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    UpCompose.future = None
    def RemoveCompose(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    RemoveCompose.future = None


  def beta_create_ComposeHandler_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('ComposeHandler', 'RemoveCompose'): ComposeIdentifier.FromString,
      ('ComposeHandler', 'UpCompose'): ComposePackage.FromString,
    }
    response_serializers = {
      ('ComposeHandler', 'RemoveCompose'): Empty.SerializeToString,
      ('ComposeHandler', 'UpCompose'): ResourceGroupCompose.SerializeToString,
    }
    method_implementations = {
      ('ComposeHandler', 'RemoveCompose'): face_utilities.unary_unary_inline(servicer.RemoveCompose),
      ('ComposeHandler', 'UpCompose'): face_utilities.unary_unary_inline(servicer.UpCompose),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ComposeHandler_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('ComposeHandler', 'RemoveCompose'): ComposeIdentifier.SerializeToString,
      ('ComposeHandler', 'UpCompose'): ComposePackage.SerializeToString,
    }
    response_deserializers = {
      ('ComposeHandler', 'RemoveCompose'): Empty.FromString,
      ('ComposeHandler', 'UpCompose'): ResourceGroupCompose.FromString,
    }
    cardinalities = {
      'RemoveCompose': cardinality.Cardinality.UNARY_UNARY,
      'UpCompose': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'ComposeHandler', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
