version: '2.1'
services:
    elastest-platform-manager:
        container_name: elastest-epm
        image: elastest/epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        expose:
            - 8180
        ports:
            - 8180:8180
        networks:
            - elastest
    epm-adapter-docker-compose:
        container_name: elastest-epm-adapter-docker-compose
        image: elastest/epm-adapter-docker-compose
        entrypoint: python run.py --register-pop
        depends_on:
            - elastest-platform-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        expose: 
            - 50051
        ports:
            - 50051:50051
        networks:
            - elastest
networks:
    elastest:
        driver: bridge
